version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_checkout:
      - git clone https://github.com/sony/nnabla-ext-cuda.git ../nnabla-ext-cuda
    pre_build:
      - VERSION=$(cat VERSION.txt) && cd ../nnabla-ext-cuda && git checkout v${VERSION}
      - ./build-tools/make/rst_for_doc.sh $(pwd)/build-doc $(pwd) ../nnabla-ext-cuda

python:
  install:
    - requirements: doc/requirements.txt

sphinx:
  configuration: doc/conf.py
